stages:
  - test
cache:
    paths:
        - node_modules/
cs:
    image: registry.docker/unit/node:6.9.1
    tags:
        - swarm
    stage: test
    script:
        - npm install
        - npm run cs

changelog:
    image: registry.docker/unit/node:6.9.1
    tags:
        - swarm
    stage: test
    before_script:
        - yum remove -y git
        - yum install -y epel-release
        - yum install -y https://centos6.iuscommunity.org/ius-release.rpm
        - yum install -y git2u-core
    script:
        - npm install
        - npm run changelog-lint

jenkins:
    image: registry.docker/unit/node:6.9.1
    tags:
        - swarm
    stage: test
    when: manual
    script:
        - npm install
        - node src/index.js build test-jubianchi
